[project]
name = "backend-ytqa-extension"
version = "0.1.0"
description = "YouTube QA Extension for Flask"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.1",
    "flask-cors>=6.0.0",
    "pydantic>=2.11.5",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
    "yt-dlp>=2025.5.22",
]
